### ISSUE TITLE
Visualization Feedback

### ISSUE THREAD

**Issue by mmmaaatttttt** [juliahazer/chart-my-team#1]
Hey Julia,

Nice work on the visualization! The styling has come a long way since I saw it on Friday; it looks great and there's a lot of functionality here.

I've broken out feedback into two pieces: feedback on the end product, and code review.

*End Product*

- In terms of functionality, there's nothing I'd like to see that I don't already see (but I also don't know much about tennis). In terms of the design, the only thing that might be nice to have is an about page or button or something that gives a high level overview of the data set. For example, what are these teams? What do all the numbers in the team names mean? That's what I found myself being curious about, but again, I know nothing about tennis :smile:

*Code Review*

- In general, it's preferable to remove commented out code rather than leaving it in the repo. Since Git tracks all your changes, if that code exists in a previous commit, you can always get back to it by looking through your history. Some examples of commented-out code that you might want to remove:

https://github.com/juliahazer/chart-my-team/blob/master/teams.py#L54-L56
https://github.com/juliahazer/chart-my-team/blob/master/app.js#L120

- your semicolon usage is a little inconsistent in `app.js`. I don't really care whether you use them or not, so long as you use them consistently.

- indentation in `app.js` also looks a bit inconsistent, like there's a mix of tabs and spaces. This is harder to see in Sublime but becomes pretty apparent on GitHub. See, for example, these lines: https://github.com/juliahazer/chart-my-team/blob/master/app.js#L327-L330

- nice use of template strings to add multiline HTML in your tooltip code!

- if you're using arrow functions for short functions anyway, i'd put them on one line so that you get the benefit of the implicit return (e.g. these lines: https://github.com/juliahazer/chart-my-team/blob/master/app.js#L265-L270)

Nice work!

**Comment by juliahazer** [comment]
Thanks so much, Matt! This is super helpful. I really appreciate you reviewing the project/code and giving this great feedback. I will plan to address your feedback and make changes this week.
